//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Backuptrngpvcoupon
    {
        public decimal AID { get; set; }
        public string CouponNo { get; set; }
        public decimal FormNo { get; set; }
        public string IdNo { get; set; }
        public string IsUsed { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public string UsedBillNo { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal UserID { get; set; }
        public decimal CouponAmt { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public decimal ProdBunchID { get; set; }
        public string IsFromSeqOffer { get; set; }
        public string BillNo { get; set; }
        public System.DateTime StartDate { get; set; }
    }
}
