//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string IdNo { get; set; }
        public Nullable<bool> Isuse { get; set; }
        public Nullable<System.DateTime> Rectimestamp { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string BillNo { get; set; }
        public Nullable<decimal> AdjustAmount { get; set; }
    }
}
