//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierCharge
    {
        public decimal AId { get; set; }
        public decimal Weight { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime RecordedTime { get; set; }
    }
}
