//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EInvoiceCredential
    {
        public int id { get; set; }
        public string Aspid { get; set; }
        public string ApiPassword { get; set; }
        public string Gstin { get; set; }
        public string Username { get; set; }
        public string EInvPwd { get; set; }
        public Nullable<System.DateTime> RectimeStamp { get; set; }
        public Nullable<System.DateTime> Modifydate { get; set; }
        public string ActiveStatus { get; set; }
    }
}
