//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedDraw
    {
        public decimal AID { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public decimal ProdCode { get; set; }
        public string ProductName { get; set; }
        public decimal BillSeq { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
    }
}
