//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPVConsistencySlab
    {
        public int AID { get; set; }
        public int MonthNo { get; set; }
        public decimal OnBVPurchase { get; set; }
        public decimal FPVWorth { get; set; }
        public string BillType { get; set; }
    }
}
