//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPVConfig
    {
        public int AID { get; set; }
        public decimal BVValue { get; set; }
        public string OnBillType { get; set; }
        public decimal FPV { get; set; }
        public string IsMultiple { get; set; }
        public string ActiveStatus { get; set; }
        public string RowStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public int ExpiredinDays { get; set; }
    }
}
