//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPVProductConfig
    {
        public int AID { get; set; }
        public decimal ProductId { get; set; }
        public string ProductName { get; set; }
        public string ActiveStatus { get; set; }
        public string RowStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public int BunchId { get; set; }
    }
}
