//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPVSlab
    {
        public decimal AID { get; set; }
        public decimal KitBV { get; set; }
        public decimal CouponAmt { get; set; }
        public string ActiveStatus { get; set; }
        public string CouponTo { get; set; }
    }
}
