//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InventoryEntities : DbContext
    {
        public InventoryEntities()
            : base("name=InventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChildProductRegistration> ChildProductRegistrations { get; set; }
        public virtual DbSet<CourierCharge> CourierCharges { get; set; }
        public virtual DbSet<DashboardSummaryColumn> DashboardSummaryColumns { get; set; }
        public virtual DbSet<DeletedChallanDetail> DeletedChallanDetails { get; set; }
        public virtual DbSet<DeletedChallanMain> DeletedChallanMains { get; set; }
        public virtual DbSet<DeletedCustomerMaster> DeletedCustomerMasters { get; set; }
        public virtual DbSet<DeletedPartyOrderDetail> DeletedPartyOrderDetails { get; set; }
        public virtual DbSet<DeletedPartyOrderMain> DeletedPartyOrderMains { get; set; }
        public virtual DbSet<DeletedProductDispatchDetail> DeletedProductDispatchDetails { get; set; }
        public virtual DbSet<DeletedPurchaseOrderDetail> DeletedPurchaseOrderDetails { get; set; }
        public virtual DbSet<DeletedPurchaseOrderMain> DeletedPurchaseOrderMains { get; set; }
        public virtual DbSet<DeletedSalesReturnDetail> DeletedSalesReturnDetails { get; set; }
        public virtual DbSet<DeletedSalesReturnMain> DeletedSalesReturnMains { get; set; }
        public virtual DbSet<DrawProduct> DrawProducts { get; set; }
        public virtual DbSet<FixedDraw> FixedDraws { get; set; }
        public virtual DbSet<FPVConfig> FPVConfigs { get; set; }
        public virtual DbSet<FPVProductConfig> FPVProductConfigs { get; set; }
        public virtual DbSet<GPVSlab> GPVSlabs { get; set; }
        public virtual DbSet<Im_CurrentStock> Im_CurrentStock { get; set; }
        public virtual DbSet<Inv_M_ConfigMaster> Inv_M_ConfigMaster { get; set; }
        public virtual DbSet<Inv_M_SearchTypeMaster> Inv_M_SearchTypeMaster { get; set; }
        public virtual DbSet<Inv_M_UserMaster> Inv_M_UserMaster { get; set; }
        public virtual DbSet<Inv_M_UserPermissionMaster> Inv_M_UserPermissionMaster { get; set; }
        public virtual DbSet<M_BankMaster> M_BankMaster { get; set; }
        public virtual DbSet<M_BarCodeMaster> M_BarCodeMaster { get; set; }
        public virtual DbSet<M_BillTypeMaster> M_BillTypeMaster { get; set; }
        public virtual DbSet<M_BlockProductMaster> M_BlockProductMaster { get; set; }
        public virtual DbSet<M_BrandMaster> M_BrandMaster { get; set; }
        public virtual DbSet<M_CardIssue> M_CardIssue { get; set; }
        public virtual DbSet<M_CatMaster> M_CatMaster { get; set; }
        public virtual DbSet<M_CityStateMaster> M_CityStateMaster { get; set; }
        public virtual DbSet<M_CompanyMaster> M_CompanyMaster { get; set; }
        public virtual DbSet<M_CompBankersMaster> M_CompBankersMaster { get; set; }
        public virtual DbSet<M_ConfigMaster> M_ConfigMaster { get; set; }
        public virtual DbSet<M_CountryMaster> M_CountryMaster { get; set; }
        public virtual DbSet<M_CouponSalesDetail> M_CouponSalesDetail { get; set; }
        public virtual DbSet<M_CourierMaster> M_CourierMaster { get; set; }
        public virtual DbSet<M_CustomerMaster> M_CustomerMaster { get; set; }
        public virtual DbSet<M_DeleteTransaction> M_DeleteTransaction { get; set; }
        public virtual DbSet<M_DispatchMaster> M_DispatchMaster { get; set; }
        public virtual DbSet<M_DispatchTypeMaster> M_DispatchTypeMaster { get; set; }
        public virtual DbSet<M_DistrictMaster> M_DistrictMaster { get; set; }
        public virtual DbSet<M_DivisionMaster> M_DivisionMaster { get; set; }
        public virtual DbSet<M_ExtraDiscount> M_ExtraDiscount { get; set; }
        public virtual DbSet<M_FiscalMaster> M_FiscalMaster { get; set; }
        public virtual DbSet<M_FormGeneration> M_FormGeneration { get; set; }
        public virtual DbSet<M_GroupMaster> M_GroupMaster { get; set; }
        public virtual DbSet<M_InsuranceCompMaster> M_InsuranceCompMaster { get; set; }
        public virtual DbSet<M_InwardMain> M_InwardMain { get; set; }
        public virtual DbSet<M_JType> M_JType { get; set; }
        public virtual DbSet<M_KitProductMaster> M_KitProductMaster { get; set; }
        public virtual DbSet<M_KitUnitMaster> M_KitUnitMaster { get; set; }
        public virtual DbSet<M_LeaderWiseOffer> M_LeaderWiseOffer { get; set; }
        public virtual DbSet<M_LedgerMaster> M_LedgerMaster { get; set; }
        public virtual DbSet<M_MenuMaster> M_MenuMaster { get; set; }
        public virtual DbSet<M_NewsSeminarMaster> M_NewsSeminarMaster { get; set; }
        public virtual DbSet<M_OccupationMaster> M_OccupationMaster { get; set; }
        public virtual DbSet<M_OfferOtherProducts> M_OfferOtherProducts { get; set; }
        public virtual DbSet<M_OfferProducts> M_OfferProducts { get; set; }
        public virtual DbSet<M_OfferType> M_OfferType { get; set; }
        public virtual DbSet<M_OtherOffers> M_OtherOffers { get; set; }
        public virtual DbSet<M_PackageProductMaster> M_PackageProductMaster { get; set; }
        public virtual DbSet<M_PartyDiscount> M_PartyDiscount { get; set; }
        public virtual DbSet<M_PayModeMaster> M_PayModeMaster { get; set; }
        public virtual DbSet<M_PlanMaster> M_PlanMaster { get; set; }
        public virtual DbSet<M_QualifyTypeMaster> M_QualifyTypeMaster { get; set; }
        public virtual DbSet<M_SearchTypeMaster> M_SearchTypeMaster { get; set; }
        public virtual DbSet<M_SpecialOfferMaster> M_SpecialOfferMaster { get; set; }
        public virtual DbSet<M_StateDivMaster> M_StateDivMaster { get; set; }
        public virtual DbSet<M_SubCatMaster> M_SubCatMaster { get; set; }
        public virtual DbSet<M_TaxBaseMaster> M_TaxBaseMaster { get; set; }
        public virtual DbSet<M_TaxCatMaster> M_TaxCatMaster { get; set; }
        public virtual DbSet<M_TaxMaster> M_TaxMaster { get; set; }
        public virtual DbSet<M_TaxTypeMaster> M_TaxTypeMaster { get; set; }
        public virtual DbSet<M_ThemeMaster> M_ThemeMaster { get; set; }
        public virtual DbSet<M_UserGroupMaster> M_UserGroupMaster { get; set; }
        public virtual DbSet<M_UserMaster> M_UserMaster { get; set; }
        public virtual DbSet<M_UserPermissionMaster> M_UserPermissionMaster { get; set; }
        public virtual DbSet<MakeKit> MakeKits { get; set; }
        public virtual DbSet<Mobile_Shoppe_MenuMaster> Mobile_Shoppe_MenuMaster { get; set; }
        public virtual DbSet<ShoppeAssignment> ShoppeAssignments { get; set; }
        public virtual DbSet<TargetDetail> TargetDetails { get; set; }
        public virtual DbSet<TargetMaster> TargetMasters { get; set; }
        public virtual DbSet<TblSlabMaster> TblSlabMasters { get; set; }
        public virtual DbSet<TempBillMain> TempBillMains { get; set; }
        public virtual DbSet<TempCourierMaster> TempCourierMasters { get; set; }
        public virtual DbSet<TempFixedDraw> TempFixedDraws { get; set; }
        public virtual DbSet<TempLeaderWiseOffer> TempLeaderWiseOffers { get; set; }
        public virtual DbSet<TempTaxMaster> TempTaxMasters { get; set; }
        public virtual DbSet<TrnBillData> TrnBillDatas { get; set; }
        public virtual DbSet<TrnBillDetail> TrnBillDetails { get; set; }
        public virtual DbSet<TrnCancelOrder> TrnCancelOrders { get; set; }
        public virtual DbSet<TrnCancelOrderDetail> TrnCancelOrderDetails { get; set; }
        public virtual DbSet<TrnCEDCoupon> TrnCEDCoupons { get; set; }
        public virtual DbSet<TrnChallanDetail> TrnChallanDetails { get; set; }
        public virtual DbSet<TrnChallanMain> TrnChallanMains { get; set; }
        public virtual DbSet<TrnCoupon> TrnCoupons { get; set; }
        public virtual DbSet<TrnCustomerDetail> TrnCustomerDetails { get; set; }
        public virtual DbSet<TrnFormGeneration> TrnFormGenerations { get; set; }
        public virtual DbSet<TrnFPVCoupon> TrnFPVCoupons { get; set; }
        public virtual DbSet<TrnGPVCoupon> TrnGPVCoupons { get; set; }
        public virtual DbSet<TrnLedger> TrnLedgers { get; set; }
        public virtual DbSet<TrnPartyOrderDetail> TrnPartyOrderDetails { get; set; }
        public virtual DbSet<TrnPartyOrderMain> TrnPartyOrderMains { get; set; }
        public virtual DbSet<TrnPaymentConfirmation> TrnPaymentConfirmations { get; set; }
        public virtual DbSet<TrnPaymentHoldDetail> TrnPaymentHoldDetails { get; set; }
        public virtual DbSet<TrnPayModeDetail> TrnPayModeDetails { get; set; }
        public virtual DbSet<TrnProductDispatchDetail> TrnProductDispatchDetails { get; set; }
        public virtual DbSet<TrnProductMain> TrnProductMains { get; set; }
        public virtual DbSet<TrnPurchaseOrderDetail> TrnPurchaseOrderDetails { get; set; }
        public virtual DbSet<TrnPurchaseOrderMain> TrnPurchaseOrderMains { get; set; }
        public virtual DbSet<TrnPurchaseReturnDetail> TrnPurchaseReturnDetails { get; set; }
        public virtual DbSet<TrnPurchaseReturnMain> TrnPurchaseReturnMains { get; set; }
        public virtual DbSet<TrnReceipt> TrnReceipts { get; set; }
        public virtual DbSet<TrnReceiptDetail> TrnReceiptDetails { get; set; }
        public virtual DbSet<TrnRewardPoint> TrnRewardPoints { get; set; }
        public virtual DbSet<TrnSalesReturnDetail> TrnSalesReturnDetails { get; set; }
        public virtual DbSet<TrnSalesReturnMain> TrnSalesReturnMains { get; set; }
        public virtual DbSet<TrnSampleProduct> TrnSampleProducts { get; set; }
        public virtual DbSet<TrnSJPCoupon> TrnSJPCoupons { get; set; }
        public virtual DbSet<TrnStockAdjustment> TrnStockAdjustments { get; set; }
        public virtual DbSet<TrnStockJv> TrnStockJvs { get; set; }
        public virtual DbSet<TrnUpdateBillDetail> TrnUpdateBillDetails { get; set; }
        public virtual DbSet<WalletReq> WalletReqs { get; set; }
        public virtual DbSet<Web_M_MenuMaster> Web_M_MenuMaster { get; set; }
        public virtual DbSet<Web_M_UserPermissionMaster> Web_M_UserPermissionMaster { get; set; }
        public virtual DbSet<Backuptrngpvcoupon> Backuptrngpvcoupons { get; set; }
        public virtual DbSet<BankBranch> BankBranches { get; set; }
        public virtual DbSet<D_sessnmaster> D_sessnmaster { get; set; }
        public virtual DbSet<DashboardSummaryColumn_> DashboardSummaryColumn_ { get; set; }
        public virtual DbSet<DeletedBillDetail> DeletedBillDetails { get; set; }
        public virtual DbSet<DeletedBillMain> DeletedBillMains { get; set; }
        public virtual DbSet<DeletedCurrentStock> DeletedCurrentStocks { get; set; }
        public virtual DbSet<DeletedInwardDetail> DeletedInwardDetails { get; set; }
        public virtual DbSet<DeletedInwardMain> DeletedInwardMains { get; set; }
        public virtual DbSet<DeletedMaxDiscount> DeletedMaxDiscounts { get; set; }
        public virtual DbSet<DeletedReceipt> DeletedReceipts { get; set; }
        public virtual DbSet<DeletedStockJv> DeletedStockJvs { get; set; }
        public virtual DbSet<DeletedVoucher> DeletedVouchers { get; set; }
        public virtual DbSet<FPVConsistencySlab> FPVConsistencySlabs { get; set; }
        public virtual DbSet<FPVProdBunch> FPVProdBunches { get; set; }
        public virtual DbSet<Inv_M_MenuMaster> Inv_M_MenuMaster { get; set; }
        public virtual DbSet<Inv_M_ThemeMaster> Inv_M_ThemeMaster { get; set; }
        public virtual DbSet<Inv_TempUserMaster> Inv_TempUserMaster { get; set; }
        public virtual DbSet<Inv_TempUserPermissionMaster> Inv_TempUserPermissionMaster { get; set; }
        public virtual DbSet<KitOffer> KitOffers { get; set; }
        public virtual DbSet<M_BillCondition> M_BillCondition { get; set; }
        public virtual DbSet<M_BloodGroupMaster> M_BloodGroupMaster { get; set; }
        public virtual DbSet<M_ChargesMaster> M_ChargesMaster { get; set; }
        public virtual DbSet<M_FlashMaster> M_FlashMaster { get; set; }
        public virtual DbSet<M_GrpPermissionMaster> M_GrpPermissionMaster { get; set; }
        public virtual DbSet<M_Initials> M_Initials { get; set; }
        public virtual DbSet<M_InvoiceTypeMaster> M_InvoiceTypeMaster { get; set; }
        public virtual DbSet<M_InwardDetail> M_InwardDetail { get; set; }
        public virtual DbSet<M_IsCardIssue> M_IsCardIssue { get; set; }
        public virtual DbSet<M_MaxDiscount> M_MaxDiscount { get; set; }
        public virtual DbSet<M_MemberMaster> M_MemberMaster { get; set; }
        public virtual DbSet<M_MonthSessnMaster> M_MonthSessnMaster { get; set; }
        public virtual DbSet<M_NewCustomer> M_NewCustomer { get; set; }
        public virtual DbSet<M_NewHOVersionInfo> M_NewHOVersionInfo { get; set; }
        public virtual DbSet<M_NewOfferMaster> M_NewOfferMaster { get; set; }
        public virtual DbSet<M_OfferProductType> M_OfferProductType { get; set; }
        public virtual DbSet<M_PartyWiseBillCondition> M_PartyWiseBillCondition { get; set; }
        public virtual DbSet<M_PKGForCustBilling> M_PKGForCustBilling { get; set; }
        public virtual DbSet<M_ProductKitUnitMaster> M_ProductKitUnitMaster { get; set; }
        public virtual DbSet<M_ProfessionMaster> M_ProfessionMaster { get; set; }
        public virtual DbSet<M_ReportType> M_ReportType { get; set; }
        public virtual DbSet<M_Reward> M_Reward { get; set; }
        public virtual DbSet<M_RewardMaster> M_RewardMaster { get; set; }
        public virtual DbSet<M_SearchMethodMaster> M_SearchMethodMaster { get; set; }
        public virtual DbSet<M_SessnMaster> M_SessnMaster { get; set; }
        public virtual DbSet<M_SpecialProductMaster> M_SpecialProductMaster { get; set; }
        public virtual DbSet<M_StockReportType> M_StockReportType { get; set; }
        public virtual DbSet<M_SubCategory> M_SubCategory { get; set; }
        public virtual DbSet<M_UserDataHistory> M_UserDataHistory { get; set; }
        public virtual DbSet<newfpv> newfpvs { get; set; }
        public virtual DbSet<ProdVoucher> ProdVouchers { get; set; }
        public virtual DbSet<ProgStock> ProgStocks { get; set; }
        public virtual DbSet<RepurchIncome> RepurchIncomes { get; set; }
        public virtual DbSet<TempBankMaster> TempBankMasters { get; set; }
        public virtual DbSet<TempBarCodeMaster> TempBarCodeMasters { get; set; }
        public virtual DbSet<TempBatchMaster> TempBatchMasters { get; set; }
        public virtual DbSet<TempBill> TempBills { get; set; }
        public virtual DbSet<TempCatMaster> TempCatMasters { get; set; }
        public virtual DbSet<TempCEDCoupon> TempCEDCoupons { get; set; }
        public virtual DbSet<TempChildProductRegistration> TempChildProductRegistrations { get; set; }
        public virtual DbSet<TempCityStateMaster> TempCityStateMasters { get; set; }
        public virtual DbSet<TempCompBankersMaster> TempCompBankersMasters { get; set; }
        public virtual DbSet<TempCoupon> TempCoupons { get; set; }
        public virtual DbSet<TempDispatchMaster> TempDispatchMasters { get; set; }
        public virtual DbSet<TempDistrictMaster> TempDistrictMasters { get; set; }
        public virtual DbSet<TempFPVCoupon> TempFPVCoupons { get; set; }
        public virtual DbSet<TempGpvcoupon> TempGpvcoupons { get; set; }
        public virtual DbSet<TempLedger> TempLedgers { get; set; }
        public virtual DbSet<TempLedgerMaster> TempLedgerMasters { get; set; }
        public virtual DbSet<TempNewHOVersionInfo> TempNewHOVersionInfoes { get; set; }
        public virtual DbSet<TempNewOfferMaster> TempNewOfferMasters { get; set; }
        public virtual DbSet<TempPartyWiseBillCondition> TempPartyWiseBillConditions { get; set; }
        public virtual DbSet<TempProductBookingMaster> TempProductBookingMasters { get; set; }
        public virtual DbSet<TempProductMaster> TempProductMasters { get; set; }
        public virtual DbSet<TempSalesReturnDetail> TempSalesReturnDetails { get; set; }
        public virtual DbSet<TempSalesReturnMain> TempSalesReturnMains { get; set; }
        public virtual DbSet<TempStateDivMaster> TempStateDivMasters { get; set; }
        public virtual DbSet<TempSubCatMaster> TempSubCatMasters { get; set; }
        public virtual DbSet<TempTaxCatMaster> TempTaxCatMasters { get; set; }
        public virtual DbSet<TempVoucher> TempVouchers { get; set; }
        public virtual DbSet<TmpBillDate> TmpBillDates { get; set; }
        public virtual DbSet<TransMaster> TransMasters { get; set; }
        public virtual DbSet<TrnBillDetails_> TrnBillDetails_ { get; set; }
        public virtual DbSet<TrnFPVCouponWronglyAssigned> TrnFPVCouponWronglyAssigneds { get; set; }
        public virtual DbSet<TrnOrderDeliveryDetail> TrnOrderDeliveryDetails { get; set; }
        public virtual DbSet<TrnPayModeMaster> TrnPayModeMasters { get; set; }
        public virtual DbSet<TrnPickListDetail> TrnPickListDetails { get; set; }
        public virtual DbSet<TrnPurchaseReqDetail> TrnPurchaseReqDetails { get; set; }
        public virtual DbSet<TrnPurchaseReqMain> TrnPurchaseReqMains { get; set; }
        public virtual DbSet<TrnVoucher> TrnVouchers { get; set; }
        public virtual DbSet<V_AccountStatement> V_AccountStatement { get; set; }
        public virtual DbSet<V_AvailProdStockBarcodes> V_AvailProdStockBarcodes { get; set; }
        public virtual DbSet<V_BillWiseOfferSummary> V_BillWiseOfferSummary { get; set; }
        public virtual DbSet<V_BillWiseSaleSummary> V_BillWiseSaleSummary { get; set; }
        public virtual DbSet<V_City> V_City { get; set; }
        public virtual DbSet<V_ConsistentOfferDetail> V_ConsistentOfferDetail { get; set; }
        public virtual DbSet<V_CurrentStockDetail> V_CurrentStockDetail { get; set; }
        public virtual DbSet<V_CurrentStockDetail_STK> V_CurrentStockDetail_STK { get; set; }
        public virtual DbSet<V_CurrentStockDetailNotForStockist> V_CurrentStockDetailNotForStockist { get; set; }
        public virtual DbSet<V_CurrentStockDetailNotForStockistNew> V_CurrentStockDetailNotForStockistNew { get; set; }
        public virtual DbSet<V_District> V_District { get; set; }
        public virtual DbSet<V_GroupWiseSaleSummary> V_GroupWiseSaleSummary { get; set; }
        public virtual DbSet<V_IDWiseBillSummary> V_IDWiseBillSummary { get; set; }
        public virtual DbSet<V_LedgerBalance> V_LedgerBalance { get; set; }
        public virtual DbSet<V_MonthWiseConsistentOffer> V_MonthWiseConsistentOffer { get; set; }
        public virtual DbSet<V_MonthWiseConsistentOffer1> V_MonthWiseConsistentOffer1 { get; set; }
        public virtual DbSet<V_MonthWiseConsistentOffer2> V_MonthWiseConsistentOffer2 { get; set; }
        public virtual DbSet<V_MonthWisePartyPurchaseSummary> V_MonthWisePartyPurchaseSummary { get; set; }
        public virtual DbSet<V_MonthWisePaymodeSummary> V_MonthWisePaymodeSummary { get; set; }
        public virtual DbSet<V_MonthWiseSaleSummary> V_MonthWiseSaleSummary { get; set; }
        public virtual DbSet<V_MonthWiseSJPConsistent> V_MonthWiseSJPConsistent { get; set; }
        public virtual DbSet<V_MonthWiseSupplierPurchaseSummary> V_MonthWiseSupplierPurchaseSummary { get; set; }
        public virtual DbSet<V_OfferProductDetail> V_OfferProductDetail { get; set; }
        public virtual DbSet<V_PartyBalance> V_PartyBalance { get; set; }
        public virtual DbSet<V_PartyDetail> V_PartyDetail { get; set; }
        public virtual DbSet<V_PartyWiseBalance> V_PartyWiseBalance { get; set; }
        public virtual DbSet<V_PaymentModeWiseDetail> V_PaymentModeWiseDetail { get; set; }
        public virtual DbSet<V_ProductStockPosition> V_ProductStockPosition { get; set; }
        public virtual DbSet<V_ProductStockPosition_STK> V_ProductStockPosition_STK { get; set; }
        public virtual DbSet<V_ProductWiseSale> V_ProductWiseSale { get; set; }
        public virtual DbSet<V_ProdWiseOfferSummary> V_ProdWiseOfferSummary { get; set; }
        public virtual DbSet<V_RptOfferSummary> V_RptOfferSummary { get; set; }
        public virtual DbSet<V_SaleReturnDetail> V_SaleReturnDetail { get; set; }
        public virtual DbSet<V_StockPlanning> V_StockPlanning { get; set; }
        public virtual DbSet<V_StockPlanningForSTKST> V_StockPlanningForSTKST { get; set; }
        public virtual DbSet<V_StockRecvSummary> V_StockRecvSummary { get; set; }
        public virtual DbSet<V_TopSellingProducts> V_TopSellingProducts { get; set; }
        public virtual DbSet<V_TransportDetail> V_TransportDetail { get; set; }
        public virtual DbSet<V_User> V_User { get; set; }
        public virtual DbSet<V_WebBillDetail> V_WebBillDetail { get; set; }
        public virtual DbSet<V_DownlineMember> V_DownlineMember { get; set; }
        public virtual DbSet<V_FPVConsistancyNew2021> V_FPVConsistancyNew2021 { get; set; }
        public virtual DbSet<M_Offers> M_Offers { get; set; }
        public virtual DbSet<M_InwardData> M_InwardData { get; set; }
        public virtual DbSet<M_ProductMaster> M_ProductMaster { get; set; }
        public virtual DbSet<TrnCPVCoupon> TrnCPVCoupons { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<FPVoucher> FPVouchers { get; set; }
        public virtual DbSet<V_CurrentStockDetailNotForStockistNewWithoutBatch> V_CurrentStockDetailNotForStockistNewWithoutBatch { get; set; }
        public virtual DbSet<M_BatchMaster> M_BatchMaster { get; set; }
        public virtual DbSet<TrnBillMain> TrnBillMains { get; set; }
        public virtual DbSet<EInvoiceCredential> EInvoiceCredentials { get; set; }
        public virtual DbSet<FPVoucherUsed> FPVoucherUseds { get; set; }
        public virtual DbSet<FPVucherWallet> FPVucherWallets { get; set; }
        public virtual DbSet<GSTMaster> GSTMasters { get; set; }
        public virtual DbSet<tblApiRequestResponse> tblApiRequestResponses { get; set; }
        public virtual DbSet<VoucherType> VoucherTypes { get; set; }
        public virtual DbSet<M_CourierDetails> M_CourierDetails { get; set; }
        public virtual DbSet<M_ShippingTax> M_ShippingTax { get; set; }
    
        [DbFunction("InventoryEntities", "MonthWiseSummary")]
        public virtual IQueryable<MonthWiseSummary_Result> MonthWiseSummary(string partyCode, string rptType)
        {
            var partyCodeParameter = partyCode != null ?
                new ObjectParameter("PartyCode", partyCode) :
                new ObjectParameter("PartyCode", typeof(string));
    
            var rptTypeParameter = rptType != null ?
                new ObjectParameter("RptType", rptType) :
                new ObjectParameter("RptType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<MonthWiseSummary_Result>("[InventoryEntities].[MonthWiseSummary](@PartyCode, @RptType)", partyCodeParameter, rptTypeParameter);
        }
    
        public virtual ObjectResult<StockDetail_Result> StockDetail(string partyCode, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var partyCodeParameter = partyCode != null ?
                new ObjectParameter("PartyCode", partyCode) :
                new ObjectParameter("PartyCode", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StockDetail_Result>("StockDetail", partyCodeParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<sp_OfferReport_Result> sp_OfferReport(string partyCode)
        {
            var partyCodeParameter = partyCode != null ?
                new ObjectParameter("PartyCode", partyCode) :
                new ObjectParameter("PartyCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_OfferReport_Result>("sp_OfferReport", partyCodeParameter);
        }
    
        public virtual ObjectResult<sp_ProdWiseOfferReport_Result> sp_ProdWiseOfferReport(string partyCode, Nullable<int> offerID)
        {
            var partyCodeParameter = partyCode != null ?
                new ObjectParameter("PartyCode", partyCode) :
                new ObjectParameter("PartyCode", typeof(string));
    
            var offerIDParameter = offerID.HasValue ?
                new ObjectParameter("OfferID", offerID) :
                new ObjectParameter("OfferID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ProdWiseOfferReport_Result>("sp_ProdWiseOfferReport", partyCodeParameter, offerIDParameter);
        }
    
        [DbFunction("InventoryEntities", "WalletReport")]
        public virtual IQueryable<WalletReport_Result1> WalletReport(string partyCode, string vtype)
        {
            var partyCodeParameter = partyCode != null ?
                new ObjectParameter("PartyCode", partyCode) :
                new ObjectParameter("PartyCode", typeof(string));
    
            var vtypeParameter = vtype != null ?
                new ObjectParameter("Vtype", vtype) :
                new ObjectParameter("Vtype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<WalletReport_Result1>("[InventoryEntities].[WalletReport](@PartyCode, @Vtype)", partyCodeParameter, vtypeParameter);
        }
    
        public virtual ObjectResult<FranchiseStockSummary_Result> FranchiseStockSummary(string partyCode, Nullable<int> month, Nullable<int> year)
        {
            var partyCodeParameter = partyCode != null ?
                new ObjectParameter("PartyCode", partyCode) :
                new ObjectParameter("PartyCode", typeof(string));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FranchiseStockSummary_Result>("FranchiseStockSummary", partyCodeParameter, monthParameter, yearParameter);
        }
    
        [DbFunction("InventoryEntities", "MobileShoppeWalletReport")]
        public virtual IQueryable<MobileShoppeWalletReport_Result> MobileShoppeWalletReport(string partyCode)
        {
            var partyCodeParameter = partyCode != null ?
                new ObjectParameter("PartyCode", partyCode) :
                new ObjectParameter("PartyCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<MobileShoppeWalletReport_Result>("[InventoryEntities].[MobileShoppeWalletReport](@PartyCode)", partyCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_GetNoOfJackpotBill(string idNo)
        {
            var idNoParameter = idNo != null ?
                new ObjectParameter("IdNo", idNo) :
                new ObjectParameter("IdNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_GetNoOfJackpotBill", idNoParameter);
        }
    
        public virtual ObjectResult<FranchiseStockSummaryNew_Result> FranchiseStockSummaryNew(string partyCode, Nullable<int> month, Nullable<int> year)
        {
            var partyCodeParameter = partyCode != null ?
                new ObjectParameter("PartyCode", partyCode) :
                new ObjectParameter("PartyCode", typeof(string));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FranchiseStockSummaryNew_Result>("FranchiseStockSummaryNew", partyCodeParameter, monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<CheckFPVoucherEligibility_Result> CheckFPVoucherEligibility(string iDno)
        {
            var iDnoParameter = iDno != null ?
                new ObjectParameter("IDno", iDno) :
                new ObjectParameter("IDno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CheckFPVoucherEligibility_Result>("CheckFPVoucherEligibility", iDnoParameter);
        }
    
        public virtual ObjectResult<sp_GetFPBalance_Result> sp_GetFPBalance(string idno, string vType)
        {
            var idnoParameter = idno != null ?
                new ObjectParameter("Idno", idno) :
                new ObjectParameter("Idno", typeof(string));
    
            var vTypeParameter = vType != null ?
                new ObjectParameter("VType", vType) :
                new ObjectParameter("VType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetFPBalance_Result>("sp_GetFPBalance", idnoParameter, vTypeParameter);
        }
    }
}
