//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Im_CurrentStock
{
    public decimal StockId { get; set; }
    public decimal FSessId { get; set; }
    public string SupplierCode { get; set; }
    public System.DateTime StockDate { get; set; }
    public string RefNo { get; set; }
    public string FCode { get; set; }
    public decimal GroupId { get; set; }
    public string ProdId { get; set; }
    public string BatchCode { get; set; }
    public string Barcode { get; set; }
    public decimal Qty { get; set; }
    public string SType { get; set; }
    public string BType { get; set; }
    public string Remarks { get; set; }
    public string ActiveStatus { get; set; }
    public string EntryBy { get; set; }
    public string StockFor { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public decimal UserId { get; set; }
    public string Version { get; set; }
    public string IsDisp { get; set; }
    public string InvoiceNo { get; set; }
    public decimal DispQty { get; set; }
    public string BillType { get; set; }
    public string ProdType { get; set; }
}

public partial class Inv_M_UserMaster
{
    public decimal UId { get; set; }
    public decimal UserId { get; set; }
    public string BranchCode { get; set; }
    public string FCode { get; set; }
    public string UserName { get; set; }
    public string Passw { get; set; }
    public string Remarks { get; set; }
    public string Status { get; set; }
    public System.DateTime CreateDate { get; set; }
    public string CreateBy { get; set; }
    public string LastIP { get; set; }
    public System.DateTime LastLoginTime { get; set; }
    public string LastLogOutTime { get; set; }
    public string Version { get; set; }
    public string LoginStatus { get; set; }
    public decimal GroupId { get; set; }
    public string ActiveStatus { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public decimal LUserId { get; set; }
    public string LastModified { get; set; }
    public string IsAdmin { get; set; }
}

public partial class M_BankMaster
{
    public decimal BId { get; set; }
    public decimal BankCode { get; set; }
    public string BankName { get; set; }
    public string IFSCode { get; set; }
    public string AcNo { get; set; }
    public string Remarks { get; set; }
    public string ActiveStatus { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public string LastModified { get; set; }
    public string UserCode { get; set; }
    public decimal UserId { get; set; }
    public string Version { get; set; }
}

public partial class M_BarCodeMaster
{
    public decimal AId { get; set; }
    public decimal BId { get; set; }
    public string GenerateBy { get; set; }
    public System.DateTime GenerateDate { get; set; }
    public string SupplierCode { get; set; }
    public string ProdId { get; set; }
    public string BatchNo { get; set; }
    public string BType { get; set; }
    public string BarCodeType { get; set; }
    public decimal BCode { get; set; }
    public string BarCode { get; set; }
    public decimal PRate { get; set; }
    public decimal MRP { get; set; }
    public decimal DP { get; set; }
    public string IsExpired { get; set; }
    public System.DateTime MfgDate { get; set; }
    public System.DateTime ExpDate { get; set; }
    public string Remarks { get; set; }
    public string ActiveStatus { get; set; }
    public string Company { get; set; }
    public string Imported { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public decimal UserId { get; set; }
    public string LastModified { get; set; }
    public decimal DP1 { get; set; }
    public decimal Val1 { get; set; }
    public decimal Val2 { get; set; }
}

public partial class M_CatMaster
{
    public decimal CatId { get; set; }
    public string CatName { get; set; }
    public string Prefix { get; set; }
    public string CatDescription { get; set; }
    public string Remarks { get; set; }
    public string ActiveStatus { get; set; }
    public string Company { get; set; }
    public decimal UserId { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public string LastModified { get; set; }
    public string OnWebSite { get; set; }
    public string IsForPC { get; set; }
    public string DelCharge { get; set; }
    public decimal WebSequence { get; set; }
}

public partial class M_CompanyMaster
{
    public decimal CId { get; set; }
    public decimal CompId { get; set; }
    public string CompName { get; set; }
    public string CompAdd { get; set; }
    public decimal CompState { get; set; }
    public string CompTinNo { get; set; }
    public string CompSTaxNo { get; set; }
    public string CompPrefix { get; set; }
    public string ContactNo { get; set; }
    public string MobileNo { get; set; }
    public string WebSite { get; set; }
    public string ActiveStatus { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public string LastModified { get; set; }
    public string UserCode { get; set; }
    public decimal UserId { get; set; }
    public string smsSenderId { get; set; }
    public string smsUserNm { get; set; }
    public string smPass { get; set; }
    public string CompMail { get; set; }
    public string CompTitle { get; set; }
    public string CompCSTNo { get; set; }
    public string CompPANNo { get; set; }
    public string MailHost { get; set; }
    public string MailPass { get; set; }
    public string CompRegOffAdd { get; set; }
    public string CompTerm { get; set; }
    public string CompanyIDNo { get; set; }
    public string MsgOnInvoice { get; set; }
    public string WebPortal { get; set; }
    public string IsSendSMS { get; set; }
    public string FTPUserNm { get; set; }
    public string FTPPassw { get; set; }
}

public partial class M_ConfigMaster
{
    public string IsGetExtreme { get; set; }
    public string IsTopup { get; set; }
    public string IsSendSMS { get; set; }
    public string IsFreeJoin { get; set; }
    public string IsStartJoin { get; set; }
    public System.DateTime JoinStartFrm { get; set; }
    public string IDNoPrefix { get; set; }
    public string IsRandomID { get; set; }
    public string IsSubPlan { get; set; }
    public string DigRandom { get; set; }
    public string IsUploadPic { get; set; }
    public string BillPrefix { get; set; }
    public string IsRefferal { get; set; }
    public string JoinStatus { get; set; }
    public string LogoutPg { get; set; }
    public string GenerateJoiningBill { get; set; }
    public string IsSubCat { get; set; }
    public string BatchPrefix { get; set; }
    public string SendMailOnBill { get; set; }
    public string SendSMSOnBill { get; set; }
}

public partial class M_FiscalMaster
{
    public decimal AutoId { get; set; }
    public decimal FSessId { get; set; }
    public System.DateTime FrmDate { get; set; }
    public System.DateTime ToDate { get; set; }
    public string FSeries { get; set; }
    public string ActiveStatus { get; set; }
    public decimal StartBillNoFrom { get; set; }
    public decimal StartUserBillNoFrom { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public string BillSeries { get; set; }
    public int StartPOFrom { get; set; }
    public int StartPIFrom { get; set; }
}

public partial class M_GroupMaster
{
    public decimal GroupId { get; set; }
    public string GroupName { get; set; }
    public string Prefix { get; set; }
    public string ActiveStatus { get; set; }
    public decimal PgroupId { get; set; }
    public decimal CommissionToParent { get; set; }
    public string OnWebsite { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public decimal PIStartFrm { get; set; }
    public decimal ChallanStartFrm { get; set; }
    public decimal BillStartFrm { get; set; }
    public string MngStkKitWs { get; set; }
    public string InvLogin { get; set; }
    public string Remarks { get; set; }
    public string AllowSTN { get; set; }
    public string SetCrLimit { get; set; }
}

public partial class M_LedgerMaster
{
    public decimal AId { get; set; }
    public decimal GroupId { get; set; }
    public decimal PGroupId { get; set; }
    public string UserPartyCode { get; set; }
    public decimal PCode { get; set; }
    public string PartyCode { get; set; }
    public string ParentPartyCode { get; set; }
    public string PartyName { get; set; }
    public string Address1 { get; set; }
    public string Address2 { get; set; }
    public decimal StateCode { get; set; }
    public decimal CityCode { get; set; }
    public string CityName { get; set; }
    public string Tehsil { get; set; }
    public decimal PinCode { get; set; }
    public string PhoneNo { get; set; }
    public decimal MobileNo { get; set; }
    public string FaxNo { get; set; }
    public string PanNo { get; set; }
    public string TinNo { get; set; }
    public string CstNo { get; set; }
    public string STaxNo { get; set; }
    public string BankAcNo { get; set; }
    public decimal BankCode { get; set; }
    public string BankName { get; set; }
    public string RequestTo { get; set; }
    public string AccountVerify { get; set; }
    public string RecommandBy { get; set; }
    public string ContactPerson { get; set; }
    public string E_MailAdd { get; set; }
    public string ActiveStatus { get; set; }
    public string OnWebSite { get; set; }
    public decimal CreditLimit { get; set; }
    public string Remarks { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public string NewFld1 { get; set; }
    public string NewFld2 { get; set; }
    public string NewFld3 { get; set; }
    public string NewFld4 { get; set; }
    public string Company { get; set; }
    public decimal UserId { get; set; }
    public string UserName { get; set; }
    public string LastModified { get; set; }
    public string RecvdCForm { get; set; }
}

public partial class M_NewHOVersionInfo
{
    public decimal AId { get; set; }
    public string LastVersionNo { get; set; }
    public string LastVersionDate { get; set; }
    public string VersionNo { get; set; }
    public string VersionDate { get; set; }
    public string VerDesc { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
}

public partial class M_PayModeMaster
{
    public decimal PId { get; set; }
    public string PayMode { get; set; }
    public string ActiveStatus { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public string Remarks { get; set; }
    public string Prefix { get; set; }
    public string IsFor { get; set; }
    public string IsShow { get; set; }
}

public partial class M_ProductMaster
{
    public decimal AId { get; set; }
    public string GenerateBy { get; set; }
    public decimal BrandCode { get; set; }
    public decimal CatId { get; set; }
    public decimal SubCatId { get; set; }
    public string ProductType { get; set; }
    public string UserProdId { get; set; }
    public decimal ProductCode { get; set; }
    public string ProdId { get; set; }
    public string ProductName { get; set; }
    public string ProductDesc { get; set; }
    public string Prefix { get; set; }
    public string ItemType { get; set; }
    public decimal BuyingTax { get; set; }
    public decimal Weight { get; set; }
    public decimal PurchaseRate { get; set; }
    public decimal MRP { get; set; }
    public decimal DP { get; set; }
    public decimal DP1 { get; set; }
    public decimal OtherStateDP { get; set; }
    public decimal Exp { get; set; }
    public decimal Costing { get; set; }
    public decimal BV { get; set; }
    public decimal CV { get; set; }
    public decimal PV { get; set; }
    public decimal RP { get; set; }
    public decimal FundPoint { get; set; }
    public string IsDiscount { get; set; }
    public decimal Discount { get; set; }
    public decimal DiscInRs { get; set; }
    public decimal VDiscount { get; set; }
    public decimal ProdCommssn { get; set; }
    public decimal GRate { get; set; }
    public decimal GMCharge { get; set; }
    public string GMType { get; set; }
    public string IsCardIssue { get; set; }
    public string Remarks { get; set; }
    public string ActiveStatus { get; set; }
    public string IsImage { get; set; }
    public string ImagePath { get; set; }
    public string OnWebSite { get; set; }
    public string TaxType { get; set; }
    public string Company { get; set; }
    public string PurchaseFrom { get; set; }
    public string PurchaseStore { get; set; }
    public string Imported { get; set; }
    public string IMEINo { get; set; }
    public string BNo { get; set; }
    public string PType { get; set; }
    public decimal BId { get; set; }
    public string BarcodeType { get; set; }
    public decimal BCode { get; set; }
    public string Barcode { get; set; }
    public string IsExpired { get; set; }
    public System.DateTime MfgDate { get; set; }
    public System.DateTime ExpDate { get; set; }
    public decimal OpStockQty { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public decimal UserId { get; set; }
    public string LastModified { get; set; }
    public decimal Val1 { get; set; }
    public decimal Val2 { get; set; }
    public string OrderDesc { get; set; }
    public string SpclOffer { get; set; }
    public string HotSell { get; set; }
    public string IsForPC { get; set; }
    public string IsFlexible { get; set; }
    public decimal SubQty { get; set; }
    public string CalcKitRate { get; set; }
    public decimal FlexiQty { get; set; }
    public string MsgText { get; set; }
    public string MsgStatus { get; set; }
    public string ImgPath1 { get; set; }
    public string ImgPath2 { get; set; }
    public string ImgPath3 { get; set; }
    public string ImgPath4 { get; set; }
    public decimal AlterID { get; set; }
}

public partial class M_SessnMaster
{
    public decimal SessID { get; set; }
    public Nullable<System.DateTime> FrmDate { get; set; }
    public Nullable<System.DateTime> ToDate { get; set; }
    public string OnWebSite { get; set; }
    public string PreExec { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public Nullable<System.DateTime> PreExecRecTimeStamp { get; set; }
    public decimal TopUpRange { get; set; }
    public string ReExec { get; set; }
    public Nullable<System.DateTime> ReExecRecTimeStamp { get; set; }
    public string FinalExec { get; set; }
    public System.DateTime FinalExeRecTimeStamp { get; set; }
    public decimal BlockSessID { get; set; }
}

public partial class M_SubCatMaster
{
    public decimal AId { get; set; }
    public decimal CatId { get; set; }
    public decimal SubCatId { get; set; }
    public string SubCatName { get; set; }
    public string Description { get; set; }
    public string Remarks { get; set; }
    public string ActiveStatus { get; set; }
    public decimal UserId { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public string LastModified { get; set; }
    public string OnWebSite { get; set; }
    public string OfferHtml { get; set; }
    public string IsForPC { get; set; }
}

public partial class M_TaxMaster
{
    public decimal AId { get; set; }
    public string GenerateBy { get; set; }
    public string ProdCode { get; set; }
    public string ProdName { get; set; }
    public decimal StateCode { get; set; }
    public decimal VatTax { get; set; }
    public decimal STax { get; set; }
    public decimal CstTax { get; set; }
    public decimal WithCForm { get; set; }
    public decimal AValue { get; set; }
    public string ActiveStatus { get; set; }
    public string Remarks { get; set; }
    public string Company { get; set; }
    public string Imported { get; set; }
    public decimal UserId { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public string LastModified { get; set; }
}

public partial class TrnBillData
{
    public decimal AId { get; set; }
    public decimal FSessId { get; set; }
    public decimal SessId { get; set; }
    public decimal SBillNo { get; set; }
    public string BillNo { get; set; }
    public string RefNo { get; set; }
    public System.DateTime BillDate { get; set; }
    public string CType { get; set; }
    public string SoldBy { get; set; }
    public string BillBy { get; set; }
    public string FType { get; set; }
    public string FCode { get; set; }
    public string PartyName { get; set; }
    public decimal SupplierId { get; set; }
    public decimal ChDDNo { get; set; }
    public Nullable<System.DateTime> ChDate { get; set; }
    public decimal ChAmt { get; set; }
    public decimal BankCode { get; set; }
    public string BankName { get; set; }
    public decimal FormNo { get; set; }
    public decimal TotalTaxAmount { get; set; }
    public decimal TotalSTaxAmount { get; set; }
    public decimal TotalDiscount { get; set; }
    public decimal TotalKitBvValue { get; set; }
    public decimal TotalBvValue { get; set; }
    public decimal TotalCVValue { get; set; }
    public decimal TotalPVValue { get; set; }
    public decimal TotalRPValue { get; set; }
    public decimal CashDiscPer { get; set; }
    public decimal CashDiscAmount { get; set; }
    public decimal NetPayable { get; set; }
    public decimal TotalAmount { get; set; }
    public decimal RndOff { get; set; }
    public decimal CardAmount { get; set; }
    public string PayMode { get; set; }
    public string PayPrefix { get; set; }
    public string BvTransfer { get; set; }
    public string Remarks { get; set; }
    public string DispatchStatus { get; set; }
    public string LR { get; set; }
    public Nullable<System.DateTime> LRDate { get; set; }
    public string TransporterName { get; set; }
    public string DispatchTo { get; set; }
    public string FreightType { get; set; }
    public decimal FreightAmt { get; set; }
    public string Series { get; set; }
    public string Scratch { get; set; }
    public decimal RefId { get; set; }
    public string RefName { get; set; }
    public string JType { get; set; }
    public decimal Unit { get; set; }
    public string BillTo { get; set; }
    public decimal PSessId { get; set; }
    public string BillFor { get; set; }
    public string DcNo { get; set; }
    public string Imported { get; set; }
    public string IsReceive { get; set; }
    public string IsCredit { get; set; }
    public string BillType { get; set; }
    public decimal TotalDiscountAmt { get; set; }
    public decimal VDiscountAmt { get; set; }
    public string ReceiverID { get; set; }
    public string ReceiverName { get; set; }
    public string ReceiverMNo { get; set; }
    public string ReceiverIDProof { get; set; }
    public decimal TotalFPoint { get; set; }
    public decimal TotalQty { get; set; }
    public decimal CommssnAmt { get; set; }
    public decimal CashReward { get; set; }
    public decimal RecvAmount { get; set; }
    public decimal ReturnToCustAmt { get; set; }
    public string ActiveStatus { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public decimal UserId { get; set; }
    public string UserName { get; set; }
    public string Version { get; set; }
    public string DelvPlace { get; set; }
    public string PaymentDtl { get; set; }
    public string IDType { get; set; }
    public string BranchName { get; set; }
    public decimal LocId { get; set; }
    public string LocName { get; set; }
    public string Pincode { get; set; }
    public decimal CourierId { get; set; }
    public string CourierName { get; set; }
    public string ProductId { get; set; }
    public string ProductName { get; set; }
    public string BatchNo { get; set; }
    public string Barcode { get; set; }
    public decimal Qty { get; set; }
    public decimal MRP { get; set; }
    public decimal DP { get; set; }
    public decimal Rate { get; set; }
    public decimal BV { get; set; }
    public decimal BVValue { get; set; }
    public decimal CV { get; set; }
    public decimal CVValue { get; set; }
    public decimal PV { get; set; }
    public decimal PVValue { get; set; }
    public decimal RP { get; set; }
    public decimal RPValue { get; set; }
    public string IsKitBV { get; set; }
    public string TaxType { get; set; }
    public decimal Tax { get; set; }
    public decimal TaxAmount { get; set; }
    public decimal SGST { get; set; }
    public decimal SGSTAmt { get; set; }
    public decimal DiscountPer { get; set; }
    public decimal Discount { get; set; }
    public decimal NetAmount { get; set; }
    public string DSeries { get; set; }
    public string DImported { get; set; }
    public string IMEINo { get; set; }
    public string BNo { get; set; }
    public string ItemType { get; set; }
    public decimal VDiscount { get; set; }
    public decimal VDiscountValue { get; set; }
    public decimal FPoint { get; set; }
    public decimal FPointValue { get; set; }
    public decimal ProdCommssn { get; set; }
    public decimal ProdCommssnAmt { get; set; }
    public string OrdStatus { get; set; }
    public decimal OrdQty { get; set; }
    public decimal RemQty { get; set; }
    public decimal DP1 { get; set; }
    public string DReason { get; set; }
    public decimal DUserId { get; set; }
    public Nullable<System.DateTime> DRecTimeStamp { get; set; }
    public decimal DocWeight { get; set; }
    public string DocketNo { get; set; }
    public Nullable<System.DateTime> DOD { get; set; }
    public string DelvAddress { get; set; }
    public string OrderNo { get; set; }
    public Nullable<System.DateTime> OrderDate { get; set; }
    public Nullable<System.DateTime> DocketDate { get; set; }
    public string DelvStatus { get; set; }
    public decimal DelvUserId { get; set; }
    public Nullable<System.DateTime> DelvRecTimeStamp { get; set; }
    public string OrderType { get; set; }
    public string UserBillNo { get; set; }
    public decimal UserSBillNo { get; set; }
    public string STNFormNo { get; set; }
    public string StkRecv { get; set; }
    public Nullable<System.DateTime> StkRecvDate { get; set; }
    public decimal StkRecvUserId { get; set; }
    public string InTransit { get; set; }
    public string UID { get; set; }
    public decimal OfferUID { get; set; }
    public string IsKit { get; set; }
    public string ProdType { get; set; }
    public string TotalCorton { get; set; }
    public string TotalMonoCorton { get; set; }
    public int SpclOfferId { get; set; }
    public decimal VAT { get; set; }
    public string BuyerAddress { get; set; }
    public string BuyerTIN { get; set; }
    public decimal CGST { get; set; }
    public decimal CGSTAmt { get; set; }
}

public partial class TrnBillDetail
{
    public decimal BillId { get; set; }
    public decimal FSessId { get; set; }
    public decimal SessId { get; set; }
    public decimal SBillNo { get; set; }
    public string BillNo { get; set; }
    public System.DateTime BillDate { get; set; }
    public decimal SupplierId { get; set; }
    public string SoldBy { get; set; }
    public string FType { get; set; }
    public string RefNo { get; set; }
    public string FCode { get; set; }
    public decimal FormNo { get; set; }
    public string ProductId { get; set; }
    public string ProductName { get; set; }
    public string BatchNo { get; set; }
    public string Barcode { get; set; }
    public decimal Qty { get; set; }
    public decimal MRP { get; set; }
    public decimal DP { get; set; }
    public decimal Rate { get; set; }
    public decimal BV { get; set; }
    public decimal BvValue { get; set; }
    public decimal CV { get; set; }
    public decimal CVValue { get; set; }
    public decimal PV { get; set; }
    public decimal PVValue { get; set; }
    public decimal RP { get; set; }
    public decimal RPValue { get; set; }
    public string IsKitBv { get; set; }
    public decimal DiscountPer { get; set; }
    public decimal Discount { get; set; }
    public decimal ProdCommssn { get; set; }
    public decimal ProdCommssnAmt { get; set; }
    public string TaxType { get; set; }
    public decimal Tax { get; set; }
    public decimal TaxAmount { get; set; }
    public decimal SGST { get; set; }
    public decimal SGSTAmt { get; set; }
    public decimal NetAmount { get; set; }
    public string Series { get; set; }
    public string Remarks { get; set; }
    public string BillFor { get; set; }
    public string Imported { get; set; }
    public string IMEINo { get; set; }
    public string BNo { get; set; }
    public string ItemType { get; set; }
    public decimal VDiscount { get; set; }
    public decimal VDiscountValue { get; set; }
    public decimal FPoint { get; set; }
    public decimal FPointValue { get; set; }
    public string ActiveStatus { get; set; }
    public decimal UserId { get; set; }
    public string Version { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public string OrdStatus { get; set; }
    public decimal OrdQty { get; set; }
    public decimal RemQty { get; set; }
    public decimal DP1 { get; set; }
    public decimal OfferUID { get; set; }
    public string IsKit { get; set; }
    public string ProdType { get; set; }
    public int SpclOfferId { get; set; }
    public decimal VAT { get; set; }
    public decimal CGST { get; set; }
    public decimal CGSTAmt { get; set; }
}

public partial class TrnBillMain
{
    public decimal BillId { get; set; }
    public decimal FSessId { get; set; }
    public decimal SBillNo { get; set; }
    public string BillNo { get; set; }
    public string RefNo { get; set; }
    public System.DateTime BillDate { get; set; }
    public string CType { get; set; }
    public string SoldBy { get; set; }
    public string BillBy { get; set; }
    public string FType { get; set; }
    public string FCode { get; set; }
    public string PartyName { get; set; }
    public decimal SupplierId { get; set; }
    public decimal ChDDNo { get; set; }
    public Nullable<System.DateTime> ChDate { get; set; }
    public decimal ChAmt { get; set; }
    public decimal BankCode { get; set; }
    public string BankName { get; set; }
    public decimal FormNo { get; set; }
    public decimal TaxAmount { get; set; }
    public decimal STaxAmount { get; set; }
    public decimal Discount { get; set; }
    public decimal KitBvValue { get; set; }
    public decimal BvValue { get; set; }
    public decimal CVValue { get; set; }
    public decimal PVValue { get; set; }
    public decimal RPValue { get; set; }
    public decimal CashDiscPer { get; set; }
    public decimal CashDiscAmount { get; set; }
    public decimal NetPayable { get; set; }
    public decimal Amount { get; set; }
    public decimal RndOff { get; set; }
    public decimal CardAmount { get; set; }
    public string PayMode { get; set; }
    public string PayPrefix { get; set; }
    public decimal SessId { get; set; }
    public string BvTransfer { get; set; }
    public string Remarks { get; set; }
    public string ActiveStatus { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public string DispatchStatus { get; set; }
    public string LR { get; set; }
    public Nullable<System.DateTime> LRDate { get; set; }
    public string TransporterName { get; set; }
    public string DispatchTo { get; set; }
    public string FreightType { get; set; }
    public decimal FreightAmt { get; set; }
    public string Series { get; set; }
    public string Scratch { get; set; }
    public decimal RefId { get; set; }
    public string RefName { get; set; }
    public string JType { get; set; }
    public decimal Unit { get; set; }
    public string BillTo { get; set; }
    public decimal PSessId { get; set; }
    public string BillFor { get; set; }
    public string DcNo { get; set; }
    public string Imported { get; set; }
    public string IsReceive { get; set; }
    public string IsCredit { get; set; }
    public string BillType { get; set; }
    public decimal DiscountAmt { get; set; }
    public decimal VDiscountAmt { get; set; }
    public string ReceiverID { get; set; }
    public string ReceiverName { get; set; }
    public string ReceiverMNo { get; set; }
    public string ReceiverIDProof { get; set; }
    public decimal TotalFPoint { get; set; }
    public decimal TotalQty { get; set; }
    public decimal CommssnAmt { get; set; }
    public decimal CashReward { get; set; }
    public decimal RecvAmount { get; set; }
    public decimal ReturnToCustAmt { get; set; }
    public string Version { get; set; }
    public decimal UserId { get; set; }
    public string UserName { get; set; }
    public string DelvPlace { get; set; }
    public string PaymentDtl { get; set; }
    public string IDType { get; set; }
    public string BranchName { get; set; }
    public decimal LocId { get; set; }
    public string LocName { get; set; }
    public string Pincode { get; set; }
    public decimal CourierId { get; set; }
    public string CourierName { get; set; }
    public decimal DocWeight { get; set; }
    public string DocketNo { get; set; }
    public Nullable<System.DateTime> DOD { get; set; }
    public string DelvAddress { get; set; }
    public string OrderNo { get; set; }
    public Nullable<System.DateTime> OrderDate { get; set; }
    public Nullable<System.DateTime> DocketDate { get; set; }
    public string DelvStatus { get; set; }
    public decimal DelvUserId { get; set; }
    public Nullable<System.DateTime> DelvRecTimeStamp { get; set; }
    public string OrderType { get; set; }
    public string UserBillNo { get; set; }
    public decimal UserSBillNo { get; set; }
    public string STNFormNo { get; set; }
    public string StkRecv { get; set; }
    public Nullable<System.DateTime> StkRecvDate { get; set; }
    public decimal StkRecvUserId { get; set; }
    public string InTransit { get; set; }
    public string UID { get; set; }
    public string TotalCorton { get; set; }
    public string TotalMonoCorton { get; set; }
    public decimal SGrNo { get; set; }
    public string GrNo { get; set; }
    public string BuyerAddress { get; set; }
    public string BuyerTIN { get; set; }
    public decimal CGSTAmt { get; set; }
}

public partial class TrnPayModeDetail
{
    public decimal AId { get; set; }
    public decimal FSessId { get; set; }
    public decimal SBillNo { get; set; }
    public string BillNo { get; set; }
    public string SoldBy { get; set; }
    public System.DateTime BillDate { get; set; }
    public string PayPrefix { get; set; }
    public string PayMode { get; set; }
    public string ChqDDNo { get; set; }
    public Nullable<System.DateTime> ChqDDDate { get; set; }
    public string CardNo { get; set; }
    public decimal BankCode { get; set; }
    public string BankName { get; set; }
    public decimal Amount { get; set; }
    public decimal BillAmt { get; set; }
    public string Narration { get; set; }
    public string ActiveStatus { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public string Version { get; set; }
    public decimal UserId { get; set; }
    public string UserName { get; set; }
    public string BillType { get; set; }
    public decimal DUserId { get; set; }
    public Nullable<System.DateTime> DRecTimeStamp { get; set; }
    public string AcNo { get; set; }
    public string IFSCode { get; set; }
}

public partial class TrnPayModeMaster
{
    public decimal ID { get; set; }
    public string PayMode { get; set; }
    public string Keyword { get; set; }
    public string ActiveStatus { get; set; }
    public string UserType { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
}

public partial class TrnStockJv
{
    public decimal OId { get; set; }
    public decimal FSessId { get; set; }
    public decimal JNo { get; set; }
    public string JvNo { get; set; }
    public System.DateTime StockDate { get; set; }
    public string SoldBy { get; set; }
    public string FCode { get; set; }
    public string PartyName { get; set; }
    public string RefNo { get; set; }
    public string ProdId { get; set; }
    public string ProductName { get; set; }
    public string BatchNo { get; set; }
    public string Barcode { get; set; }
    public decimal Qty { get; set; }
    public string JType { get; set; }
    public string Remarks { get; set; }
    public System.DateTime RecTimeStamp { get; set; }
    public decimal UserId { get; set; }
    public string UserName { get; set; }
    public string Version { get; set; }
    public string ActiveStatus { get; set; }
    public string ProdType { get; set; }
}

public partial class V_BillWiseSaleSummary
{
    public decimal FSessId { get; set; }
    public string OrderNo { get; set; }
    public Nullable<System.DateTime> OrderDate { get; set; }
    public decimal UserSBillNo { get; set; }
    public string UserBillNo { get; set; }
    public decimal SBillNo { get; set; }
    public string BillNo { get; set; }
    public System.DateTime BillDate { get; set; }
    public Nullable<decimal> GroupId { get; set; }
    public string GroupName { get; set; }
    public string PartyCode { get; set; }
    public string PartyName { get; set; }
    public string FCode { get; set; }
    public string NewFCode { get; set; }
    public string Name { get; set; }
    public string OrderType { get; set; }
    public string DownIDNo { get; set; }
    public string DownMemName { get; set; }
    public decimal BVValue { get; set; }
    public decimal RPValue { get; set; }
    public decimal Amount { get; set; }
    public decimal TaxAmount { get; set; }
    public Nullable<decimal> NetAmt { get; set; }
    public string PayMode { get; set; }
    public decimal RefId { get; set; }
    public string RefName { get; set; }
    public string KitName { get; set; }
    public string Series { get; set; }
    public string BType { get; set; }
    public string BillType { get; set; }
    public string IsReceive { get; set; }
    public string FType { get; set; }
    public string Remarks { get; set; }
    public string DispatchStatus { get; set; }
}

public partial class V_CurrentStockDetailNotForStockist
{
    public string PartyCode { get; set; }
    public string PartyName { get; set; }
    public decimal CatId { get; set; }
    public string CatName { get; set; }
    public string ProdId { get; set; }
    public string ProductName { get; set; }
    public string BatchCode { get; set; }
    public string Barcode { get; set; }
    public string MinStockQty { get; set; }
    public decimal PurchaseRate { get; set; }
    public System.DateTime MfgDate { get; set; }
    public System.DateTime ExpDate { get; set; }
    public decimal DP { get; set; }
    public decimal MRP { get; set; }
    public decimal RP { get; set; }
    public decimal Qty { get; set; }
    public decimal KitProdQty { get; set; }
    public decimal NSProdQty { get; set; }
    public Nullable<decimal> TotalQty { get; set; }
    public Nullable<decimal> RPValue { get; set; }
    public Nullable<decimal> StockValue { get; set; }
    public Nullable<decimal> DPStockValue { get; set; }
    public Nullable<decimal> MRPStockValue { get; set; }
}
