//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CourierDetails
    {
        public decimal Id { get; set; }
        public Nullable<decimal> CourierId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<System.DateTime> RecTimeStamp { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> UserId { get; set; }
    }
}
