//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_OfferProducts
    {
        public decimal AID { get; set; }
        public decimal OfferID { get; set; }
        public string ProdID { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RectimeStamp { get; set; }
        public decimal Qty { get; set; }
        public decimal FreeQty { get; set; }
        public string IsFlexible { get; set; }
        public Nullable<decimal> OfferMrp { get; set; }
        public string IsBuyProduct { get; set; }
    }
}
