//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_OtherOffers
    {
        public int AID { get; set; }
        public int OfferID { get; set; }
        public string OfferName { get; set; }
        public decimal MinBV { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int StartProduct { get; set; }
        public string ActiveStatus { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public string ForFranchise { get; set; }
        public decimal OfferOnToBV { get; set; }
        public string Forbill { get; set; }
    }
}
