//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ShippingTax
    {
        public decimal Aid { get; set; }
        public string BillNo { get; set; }
        public Nullable<decimal> ShippingAmt { get; set; }
        public Nullable<decimal> ShippingPer { get; set; }
        public string Shippingtype { get; set; }
        public Nullable<decimal> ShippingTaxCGST { get; set; }
        public Nullable<decimal> ShippingTaxSGST { get; set; }
        public Nullable<decimal> ShippingTaxIGST { get; set; }
        public Nullable<System.DateTime> RecTimeStamp { get; set; }
        public Nullable<decimal> Prodid { get; set; }
        public Nullable<decimal> ShippingProdid { get; set; }
    }
}
