//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgStock
    {
        public Nullable<double> Srl_No { get; set; }
        public string Product_Name { get; set; }
        public Nullable<double> Stock_Opening { get; set; }
        public Nullable<double> Stock_In { get; set; }
        public Nullable<double> Stock_Out { get; set; }
        public Nullable<double> Stock_Balance { get; set; }
        public Nullable<double> RCP { get; set; }
        public Nullable<double> Total { get; set; }
        public string PartyCode { get; set; }
        public string ProdID { get; set; }
    }
}
