//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppeAssignment
    {
        public decimal AId { get; set; }
        public string FCode { get; set; }
        public string PCId { get; set; }
        public System.DateTime RecordedTime { get; set; }
        public string PCName { get; set; }
        public string FormNo { get; set; }
    }
}
