//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApiRequestResponse
    {
        public int id { get; set; }
        public string UserBillNo { get; set; }
        public string ApiURL { get; set; }
        public string Request { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> RestimeStamp { get; set; }
        public string Error { get; set; }
        public string Entrytype { get; set; }
        public Nullable<decimal> Billrefid { get; set; }
    }
}
