//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSlabMaster
    {
        public int ID { get; set; }
        public Nullable<int> FromSlab { get; set; }
        public Nullable<int> ToSlab { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> RpPoint { get; set; }
    }
}
