//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempBillMain
    {
        public decimal BillId { get; set; }
        public string BillNo { get; set; }
        public decimal SBillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public string SoldBy { get; set; }
        public string Fcode { get; set; }
        public decimal FormNo { get; set; }
        public decimal TotalBv { get; set; }
        public decimal TotalKitBv { get; set; }
        public decimal Amount { get; set; }
        public decimal SessId { get; set; }
        public string BvTransfer { get; set; }
        public decimal TaxAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
