//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnCustomerDetail
    {
        public decimal AId { get; set; }
        public string CustomerName { get; set; }
        public string MobileNo { get; set; }
        public string BillNo { get; set; }
        public string ActiveStatus { get; set; }
        public string Address1 { get; set; }
    }
}
