//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnSJPCoupon
    {
        public decimal AID { get; set; }
        public string CouponNo { get; set; }
        public string IsUsed { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public string UsedBillNo { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal CouponAmt { get; set; }
        public string IDno { get; set; }
        public string ForBillNo { get; set; }
    }
}
