//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BillWiseOfferSummary
    {
        public string UserBillNo { get; set; }
        public string BillDateStr { get; set; }
        public string FCode { get; set; }
        public string PartyName { get; set; }
        public string SoldBy { get; set; }
        public decimal OfferUID { get; set; }
        public string OfferType { get; set; }
        public string OfferName { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string BillNo { get; set; }
        public Nullable<decimal> TotalSale { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> FreeQty { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public Nullable<decimal> FreeProdValue { get; set; }
        public Nullable<decimal> AmtCollected { get; set; }
        public Nullable<decimal> OfferValue { get; set; }
    }
}
