//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FPVConsistancyNew2021
    {
        public string FCode { get; set; }
        public System.DateTime billdate { get; set; }
        public string userBillno { get; set; }
        public string billNo { get; set; }
        public string MemName { get; set; }
        public decimal Mobl { get; set; }
        public string City { get; set; }
        public string IdNo { get; set; }
        public string INTName { get; set; }
        public decimal INTMobie { get; set; }
    }
}
