//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MonthWiseConsistentOffer
    {
        public string IDNo { get; set; }
        public string MemName { get; set; }
        public decimal Mobl { get; set; }
        public string City { get; set; }
        public decimal Formno { get; set; }
        public string FebD { get; set; }
        public Nullable<decimal> FebAmt { get; set; }
        public string MarD { get; set; }
        public Nullable<decimal> MarAmt { get; set; }
        public string AprD { get; set; }
        public Nullable<decimal> AprAmt { get; set; }
        public string MayD { get; set; }
        public Nullable<decimal> MayAmt { get; set; }
        public string JunD { get; set; }
        public Nullable<decimal> JunAmt { get; set; }
        public string JulD { get; set; }
        public Nullable<decimal> JulAmt { get; set; }
        public string AugD { get; set; }
        public Nullable<decimal> AugAmt { get; set; }
        public string SepD { get; set; }
        public Nullable<decimal> SepAmt { get; set; }
        public string OctD { get; set; }
        public Nullable<decimal> OctAmt { get; set; }
        public string NovD { get; set; }
        public Nullable<decimal> NovAmt { get; set; }
        public string DecD { get; set; }
        public Nullable<decimal> DecAmt { get; set; }
    }
}
