//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MonthWiseConsistentOffer1
    {
        public string IDNo { get; set; }
        public string MemName { get; set; }
        public decimal Mobl { get; set; }
        public string City { get; set; }
        public decimal Formno { get; set; }
        public System.DateTime RecTimeStamp { get; set; }
        public decimal CouponAmt { get; set; }
        public string UserBillNo { get; set; }
    }
}
