//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MonthWiseConsistentOffer2
    {
        public string IDNo { get; set; }
        public string MemName { get; set; }
        public decimal Mobl { get; set; }
        public string City { get; set; }
        public decimal Formno { get; set; }
        public string FebD { get; set; }
        public Nullable<decimal> FebAmt { get; set; }
        public string FebBill { get; set; }
        public string MarD { get; set; }
        public Nullable<decimal> MarAmt { get; set; }
        public string MarBill { get; set; }
        public string AprD { get; set; }
        public Nullable<decimal> AprAmt { get; set; }
        public string AprBill { get; set; }
        public string MayD { get; set; }
        public Nullable<decimal> MayAmt { get; set; }
        public string MayBill { get; set; }
        public string JunD { get; set; }
        public Nullable<decimal> JunAmt { get; set; }
        public string JunBill { get; set; }
        public string JulD { get; set; }
        public Nullable<decimal> JulAmt { get; set; }
        public string JulBill { get; set; }
        public string AugD { get; set; }
        public Nullable<decimal> AugAmt { get; set; }
        public string AugBill { get; set; }
        public string SepD { get; set; }
        public Nullable<decimal> SepAmt { get; set; }
        public string SepBill { get; set; }
        public string OctD { get; set; }
        public Nullable<decimal> OctAmt { get; set; }
        public string OctBill { get; set; }
        public string NovD { get; set; }
        public Nullable<decimal> NovAmt { get; set; }
        public string NovBill { get; set; }
        public string DecD { get; set; }
        public Nullable<decimal> DecAmt { get; set; }
        public string DecBill { get; set; }
        public string JanD2020 { get; set; }
        public Nullable<decimal> JanAmt2020 { get; set; }
        public string JanBill2020 { get; set; }
        public string FebD2020 { get; set; }
        public Nullable<decimal> FebAmt2020 { get; set; }
        public string FebBill2020 { get; set; }
        public string MarD2020 { get; set; }
        public Nullable<decimal> MarAmt2020 { get; set; }
        public string MarBill2020 { get; set; }
        public string AprD2020 { get; set; }
        public Nullable<decimal> AprAmt2020 { get; set; }
        public string AprBill2020 { get; set; }
        public string MayD2020 { get; set; }
        public Nullable<decimal> MayAmt2020 { get; set; }
        public string MayBill2020 { get; set; }
        public string JunD2020 { get; set; }
        public Nullable<decimal> JunAmt2020 { get; set; }
        public string JunBill2020 { get; set; }
        public string JulD2020 { get; set; }
        public Nullable<decimal> JulAmt2020 { get; set; }
        public string JulBill2020 { get; set; }
        public string AugD2020 { get; set; }
        public Nullable<decimal> AugAmt2020 { get; set; }
        public string AugBill2020 { get; set; }
        public string SepD2020 { get; set; }
        public Nullable<decimal> SepAmt2020 { get; set; }
        public string SepBill2020 { get; set; }
        public string OctD2020 { get; set; }
        public Nullable<decimal> OctAmt2020 { get; set; }
        public string OctBill2020 { get; set; }
        public string NovD2020 { get; set; }
        public Nullable<decimal> NovAmt2020 { get; set; }
        public string NovBill2020 { get; set; }
        public string DecD2020 { get; set; }
        public Nullable<decimal> DecAmt2020 { get; set; }
        public string DecBill2020 { get; set; }
    }
}
