//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MonthWisePaymodeSummary
    {
        public string SoldBy { get; set; }
        public string SoldByName { get; set; }
        public Nullable<int> Yr { get; set; }
        public Nullable<int> Mnth { get; set; }
        public string MnthName { get; set; }
        public Nullable<decimal> BillAmt { get; set; }
        public Nullable<decimal> CashAmt { get; set; }
        public Nullable<decimal> ChqAmt { get; set; }
        public Nullable<decimal> DDAmt { get; set; }
        public Nullable<decimal> CreditCardAmt { get; set; }
        public Nullable<decimal> BankDeposit { get; set; }
        public Nullable<decimal> NEFTRTGS { get; set; }
        public Nullable<decimal> DebitCardAmt { get; set; }
        public Nullable<decimal> NetBanking { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> WalletAmt { get; set; }
        public Nullable<decimal> VoucherAmt { get; set; }
        public Nullable<decimal> PaytmAmt { get; set; }
        public Nullable<decimal> IMPSAmt { get; set; }
        public Nullable<decimal> RepWallet { get; set; }
        public Nullable<decimal> AdvWallet { get; set; }
        public Nullable<decimal> VDiscountAmt { get; set; }
        public Nullable<decimal> NetAmt { get; set; }
        public Nullable<decimal> ExcessAmt { get; set; }
        public Nullable<decimal> NetPayable { get; set; }
        public Nullable<decimal> PVPurchaseWallet { get; set; }
        public Nullable<decimal> BVPurchaseWallet { get; set; }
    }
}
