//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ProdWiseOfferSummary
    {
        public string SoldBy { get; set; }
        public decimal OfferID { get; set; }
        public string ProdID { get; set; }
        public string ProductName { get; set; }
        public string UserProdID { get; set; }
        public decimal FreeQty { get; set; }
        public decimal FreeProdValue { get; set; }
        public decimal AmtCollected { get; set; }
        public decimal OfferValue { get; set; }
    }
}
